name: dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2
  - matplotlib=3.8
  - geopandas=0.14
  - pyogrio=0.7
  - pyproj=3.6
  - shapely=2.0
  - fiona=1.9
  - pip
  - pip:
      - shiny
      - shinywidgets
      - ipyleaflet
      - plotly